# NATS
nats:
  subject: "subject"
  natsURL: "0.0.0.0:4222"
#PostgreSQL
postgresql: 
  database_URL: "host=localhost port=5432 user=postgres password=1234 dbname=wildtest sslmode=disable"
#Router
bind_addr: ":8084"